In [ ]:
import numpy as np

Part 1: Creating and Reshaping Arrays
1. Create Arrays:
  - Create two NumPy arrays:
    - A 1D array of 10 equally spaced values between 0 and 50.
    - A 2D array of shape (3x3) containing random integers
between 5 and 20.
2. Array Dimensions:
  - Print the dimensions of both arrays.
  - Print the shape of both arrays.
3. Reshaping:
- Reshape the 1D array into a 2D array with shape (2x5).
- Print the reshaped array.
- Flatten the reshaped array back to 1D and print it.

In [ ]:
# 1. Create Arrays:
arr = np.linspace(0,51,10)
arr2 = np.array([np.random.randint(5,20,3),
                 np.random.randint(5,20,3),
                 np.random.randint(5,20,3)])

print(arr2)
# 2. Array Dimensions:
print("array 1: ",arr.ndim)
print("array 2: ",arr2.ndim)

print("array 1: ",arr.shape)
print("array 2: ",arr2.shape)

# 3. Reshaping:
res = arr.reshape(2,5)
print("reshaped array 1: ", res)
fla = res.reshape(-1)
print("flattened array 1: ", fla)


2

Part 2: Indexing and Slicing:

4. Indexing:
- For the 2D array created in Part 1, print the element present at the 2nd row and 3rd column.
- Extract the first two rows and the last two columns of the array.

5. Slicing:
- Slice the first four elements from the flattened 1D array.
- Reverse the elements of the 1D array using slicing

In [ ]:
# 4. Indexing
print(arr2[1,2])
print(arr2[:2,1:])
# 5. Slicing
print(arr[4:])
print(arr[::-1])


Part 3: Array Operations

6. Array Arithmetic:
- Create another 1D array of 10 integers between 1 and 10.
- Perform the following element-wise operations between the 1D
arrays created in Part 1 and Part 3:
    - Addition
    - Multiplication
    - Subtract a constant value (e.g., 5) from the array.

In [ ]:
# 6. Array Arithmetic:
arr1 = np.array([1,2,3,4,5,6,7,8,9,0])
add = np.add(arr,arr1)
mul = np.multiply(arr,arr1)
sub = np.subtract(arr,5)
print(add)
print(mul)
print(sub)

Part 4: Random Number Generation and Copying

7. Random Numbers:
- Create a 1D array of 5 random values between 0 and 1.
- Create another 1D array of 5 random values between -1 and 1.

In [ ]:
# 7. Random Numbers:
arr = np.array([np.random.rand(5)])
print(arr)
arr1 = np.array([np.random.randint(-1,1,5)])
print(arr1)

Part 5: Bonus

8. Challenge Task:
- Write a program that asks the user to input a number (n), and then
generates an n x n array of random integers between 1 and 100.
- Find the sum of all the elements in the array and print the result

In [ ]:
# 8. Challenge Task:
n = int(input())
arr2 = np.array([np.random.randint(1,100,n*n)])
print(arr2.reshape(n,n))
add = np.sum(arr2[:])
print(add)

3
[[65 96  4]
 [18 13 49]
 [63  6 31]]
345
